version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: iauditor_exporter_db
      POSTGRES_USER: iauditor_exporter
      POSTGRES_PASSWORD: iauditor_exporter
    ports:
      - 5434:5432

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: iauditor_exporter
      MYSQL_DATABASE: iauditor_exporter_db
      MYSQL_USER: iauditor_exporter
      MYSQL_PASSWORD: iauditor_exporter
    ports:
      - 3308:3306

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "iAuditorExporter12345"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
