# yamllint disable rule:line-length
---
name: Tests

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test & Coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          go test -coverprofile c.out ./...
          ./cc-test-reporter after-build --prefix $(go list -m)

      - uses: actions/setup-python@v2
      - name: Run pre commit linting
        uses: pre-commit/action@v2.0.0

  PostgreSQL-Integration-Tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: iauditor_exporter_db
          POSTGRES_USER: iauditor_exporter
          POSTGRES_PASSWORD: iauditor_exporter
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test & Coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          TEST_DB_DIALECT: postgres
          TEST_DB_CONN_STRING: "postgresql://iauditor_exporter:iauditor_exporter@localhost:5434/iauditor_exporter_db"
        run: |
          go test ./... -tags=sql
